### ISSUE TITLE
synchronize_and_start_cameras() is depcrecated

### ISSUE THREAD

**Issue by knelk** [prophesee-ai/prophesee_ros_stereo_driver#4]
the synchronize_and_start_cameras() function is depcracated since version 2.1.0  (https://docs.prophesee.ai/metavision_sdk/modules/driver/api/camera.html#_CPPv4N10Metavision6Camera29synchronize_and_start_camerasER6CameraR6Camera)

is the hardware synch the only current alternative to synch two cameras? or do you still have a software synch function available (planned)?

**Comment by laurentbristiel** [comment]
To sync 2 cameras, you can connect them using a synchronization cable. One of the camera will be the master camera, while the other will be the slave camera. Specifically, the TRIGGER_OUT/EXT_SYNC_CLK_OUT signal of the master camera needs to be connected to the EXT_SYNC_CLK_IN signal of the slave camera.

You can see our [metavision_hal_sync.cpp sample](https://docs.prophesee.ai/stable/metavision_sdk/modules/metavision_hal/samples/hal_sync.html#chapter-hal-samples-hal-sync) for informations and links to other explanations.
